### ISSUE TITLE
[GSF Principles] Help write the new version of the Principles of Green Software Engineering

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/green-software-principles#10]
We are working to upgrade the principles of green software engineering, http://principles.green looking for writers, editors, people with opinions, thoughts and advice to help re-define the new principles.

See more details here: https://github.com/Green-Software-Foundation/principles/discussions

Please respond to this issue if you are interested or email helpdesk@greensoftware.foundation

**Comment by kunalmcitm** [comment]
Am interested

**Comment by ianstokesrees-gamma** [comment]
I am interested in this as well, with a BCG perspective.  However I noted on that webpage:

> A personal project by Asim Hussain, Green Cloud Advocacy Lead at Microsoft. Further training based on the Principles of Green Software Engineering is available on the Microsoft Learn platform.

I am not sure what mandate we have to "refine" someone elses personal (and copyrighted) work.

**Comment by iloabn** [comment]
> I am not sure what mandate we have to "refine" someone elses personal (and copyrighted) work.

@ianstokesrees-gamma That personal project, created by "Asim Hussain" that you're mentioning, that also happens to be @jawache , the Executive Director at the green software foundation and the creator os this issue. I think we're good in terms of mandate 😊
Super cool that you're interested in joining the effort of the Green Software Foundation and that you wanted to make sure nobody's work was infringed in any way.

**Comment by dubrie** [comment]
I am interested in helping out!
