### ISSUE TITLE
Action for visibility and community engagement 

### ISSUE THREAD

**Issue by CodeThePast** [Green-Software-Foundation/green-software-principles#11]
In the light of extending knowledge about Green Software, I wonder if we can engage in the recent campaign [WikiForHumanRights: Right to a Healthy Environment](https://diff.wikimedia.org/2021/12/01/were-back-for-wikiforhumanrights-in-2022/).

If we want to "communicate with others regarding Green software, share a language and a dictionary" would be useful to expand visibility and understanding of the many complex issues related with the topic. We all know that for many people (and many of us) Wikipedia is a great source for knowledge and a daily tool. Are we sure that information reported for example on [Green Computing](https://en.wikipedia.org/wiki/Green_computing) or [Computational Sustainability](https://en.wikipedia.org/wiki/Computational_sustainability) Wikipedia pages cannot be further refined or expanded? With my fresh and still limited software skills, and great interest in the green software field, as a Wikimedia contributor I would like to help with that.

Wikimedia is a large institution and its worldwide community is very active and sensitive to social issues, I am sure we can have great support. If you have some interest in this idea I inform you there will be a community conversation hour on December 14th to learn more and discuss about how to participate to the Wikimedia campaign.

Open to hear your opinion. Bye.

**Comment by greenhsu123** [comment]
thank you for starting this discussion, and sharing the resources!
It certainly looks like a very worthy cause to consider, let's further this discussion at the community wg meeting later!

**Comment by CodeThePast** [comment]
Yes, it would be nice to work on that. Hope someone will be interested at Wikimedia as well.
