### ISSUE TITLE
[Principles Section 1] proofread Carbon including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#38]
[Carbon](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Carbon.md)

**Comment by nicocsm** [comment]
Looking into graphics idea

**Comment by akshitbatra** [comment]
Graphics idea suggestions: 
1. With Greenhouse gases section, we can add an infographic for comparison of GWP (Global Warming Potentials) comparison with mostly common GHGs and the ones which are mentioned in the example.
2. With COP / Paris Climate Agreement, we can create an infographic representing the text in numerical/statistical form for a better skim experience or for saving image for future reference.
3. With Climate and Us, In this we can add real photos how GHGs are affecting the environment like melting or glaciers, sea level rising. or we can also create an infographic showing how environment is affected.

**Comment by nicocsm** [comment]
Image ideas:
1. [Greenhouse gases](https://en.wikipedia.org/wiki/Greenhouse_gas#/media/File:Greenhouse-effect-t2.svg)
2. [Climate and Us](https://www.iberdrola.com/documents/20125/40258/Infographic_Impact_climate_change.pdf/ace32376-acfd-657a-58c7-a8697e79f4fc?t=1634806271193)

**Comment by dubrie** [comment]
> [Carbon](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Carbon.md)

The link to Carbon is 404ing because it's a capital C in the Carbon.md file, this link to [Carbon](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/carbon.md) uses the lowercase c and should work

**Comment by greenhsu123** [comment]
Completed!
