### ISSUE TITLE
[Principles Section 2] proofread Electricity including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#39]
[Electricity](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Electricity.md)

**Comment by markus-ntt-seidl** [comment]
https://github.com/Green-Software-Foundation/green-software-principles/blob/09f6a1aed4b4adf8c9ceb43caa0a45a5058dcd78/Principles/Electricity.md?plain=1#L29

Minor Point: It's stated that only running applications need energy. While this is theoretically true, also not-running applications need energy, as resources are provisioned and are active for the application to run on them.

https://github.com/Green-Software-Foundation/green-software-principles/blob/09f6a1aed4b4adf8c9ceb43caa0a45a5058dcd78/Principles/Electricity.md?plain=1#L37

* The image suggestion here is easy, do a graph or a nice representation showing the current energy consumption world wide. I think https://en.wikipedia.org/wiki/World_energy_supply_and_consumption should provide enough data and graph examples
* 49% is no longer true, see https://en.wikipedia.org/wiki/World_energy_supply_and_consumption . It's more close to 83,1% (Oil, Coal and Gas in 2020) .

**Comment by markus-ntt-seidl** [comment]
I wanted to create a PR for the changes mentioned above, but the Electricity file has vanished. It has been removed from the dev branch. It still exists in the commit 09f6a1a though.
If I do a PR I guess no one would see any changes and this makes comparing it difficult

@greenhsu123 or @jawache  (or anyone else with rights): Can you restore the draft in some branch? Thanks!

**Comment by dubrie** [comment]
> [Electricity](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Electricity.md)

This link is broken because the Markdown file is capitalized, using the lowercase filename works: [Electricity](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/electricity.md)

**Comment by greenhsu123** [comment]
Completed!
