### ISSUE TITLE
[Principles Section 0] proofread Introduction including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#40]
proofread [Introduction](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Introduction.md) including graphics for summit's deck

**Comment by akshitbatra** [comment]
Graphic Suggestion:
1. With 'What is Green Software' section, we can create an infographic for the flow chart of how we classify software in carbon efficient and carbon aware and what factors we consider while in the process.

**Comment by greenhsu123** [comment]
We could consider citing this image from The State of Green Cloud Software Practices in 2022
![image](https://user-images.githubusercontent.com/88226967/164653432-77908deb-c016-45dd-91b0-f05c55493b52.png)

**Comment by dubrie** [comment]
From the foundation website on [What is Green Software](https://greensoftware.foundation/articles/what-is-green-software) it states the 3 ways to reduce emissions as:
1. Using less physical resources
1. Using less energy
1. Using energy more intelligently

Should we invert the image above to frame this more directly in the verbiage the foundation uses on the site? Something like this: (excuse my poor graphic design skills)

![image](https://user-images.githubusercontent.com/436997/167032552-7ce76b55-eecb-4879-affd-ad9029022531.png)

**Comment by greenhsu123** [comment]
Completed!
