### ISSUE TITLE
[Principles Section 3] proofread Carbon Intensity including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#41]
[Carbon Intensity](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/carbon-intensity.md)

**Comment by ccasher** [comment]
Line: https://github.com/Green-Software-Foundation/green-software-principles/blob/4c88ee055726fc416574513da453b16e698fd945/Principles/carbon-intensity.md?plain=1#L36

Image Suggestion: https://media.nationalgeographic.org/assets/photos/000/327/32787.jpg

**Comment by ccasher** [comment]
https://github.com/Green-Software-Foundation/green-software-principles/blob/4c88ee055726fc416574513da453b16e698fd945/Principles/carbon-intensity.md?plain=1#L48

https://github.com/Green-Software-Foundation/green-software-principles/blob/4c88ee055726fc416574513da453b16e698fd945/Principles/carbon-intensity.md?plain=1#L156

The Spacial and Temporal shifting sections are kind of redundant with the Variability of Carbon Intensity section above

**Comment by greenhsu123** [comment]
Completed!
