### ISSUE TITLE
[Principles Section 5] proofread Neutralisations including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#43]
[Principles] proofread Neutralisations including graphics for summit's deck. Also merge https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/Neutralisations.md and https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/understanding-corporate-targets.md

**Comment by greenhsu123** [comment]
@nicocsm

**Comment by nicocsm** [comment]
Merged content from Neutralisations.md into understanding-corporate-targets.md. PR #47 & #48 raised

**Comment by greenhsu123** [comment]
Completed!
