### ISSUE TITLE
[Principles Section 6] proofread Measurement including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#44]
[Principles] proofread Measurementincluding graphics for summit's deck.

**Comment by markus-ntt-seidl** [comment]
I fail to find that section, do you have a link?

**Comment by akshitbatra** [comment]
@markus-ntt-seidl 

It is still in pull request I guess.
Here is the link of pull request: https://github.com/Green-Software-Foundation/green-software-principles/pull/50

**Comment by greenhsu123** [comment]
Completed!
