### ISSUE TITLE
Embodied Carbon Claim that software cannot help breakdown of hardware

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-principles#66]
I think we should be careful how we phrase this part:

> Hardware is retired either because it breaks down or struggles to handle modern workloads. The software cannot help with the first. However, if we focus on building applications that can run on older hardware, we can help with the second.

While I agree that software won't have a large effect on hardware breaking down, it certainly has an impact. For example, running a machine in a constantly overclocked state, or "hot", will decrease the overall lifetime of its components (and requires additional cooling which further impacts emissions). Some studies have shown ~70% frequency optimizes the power:output ratio and can extend the lifetime of a CPU. Other approaches like architecting for a microservices infrastructure can reduce the load of an individual machine and spread it out across multiple ones. These decisions may not be the most sustainable overall, but they can have an impact on the lifetime of hardware.

**Comment by jawache** [comment]
That makes sense @dubrie, do you have some alternative wording?

**Comment by dubrie** [comment]
Just submitted a pull request for it: https://github.com/Green-Software-Foundation/green-software-principles/pull/74
